### ISSUE TITLE
Unwanted submit by click on [close] or [clear]

### ISSUE THREAD

**Issue by mostafa-norouzi** [amsify42/jquery.amsify.select#3]
Hi ,
And thank you for this handy plugin.

I noticed that in a simple structure, **form submitted when user click on clear button or close!**
and can be fixed by adding type to these two buttons like :

```
var clear                 = '<button type="button"
....
....
var close                 = '<button type="button"
```

(checked in google chrome)
with best.

**Comment by amsify42** [comment]
Hi,
Thank you for the suggestion, I made this change and published the package.
