### ISSUE TITLE
Closing the list automatically after an item selected?

### ISSUE THREAD

**Issue by mostafa-norouzi** [amsify42/jquery.amsify.select#4]
Hi

I need to close the list just after user selects one item.
can you guide me how to edit?

Thank you in advanced.

**Comment by mostafa-norouzi** [comment]
Currently I added below code to near line  315

```
			$(this.selectors.label).text(label);
			$(this.selector).change();
			//console.info($(this.selector).val());
315			$(_self.selectors.listArea).hide();//mosi hack :: hide list after select
```

And working properly.

**Comment by amsify42** [comment]
Thank you for pointing out this issue, I fixed it and published the new minor version.
I am hiding the list once the item is selected in single select option.

**Comment by mostafa-norouzi** [comment]
So fast like the plugin! Thank you 🌷
